apiVersion: v1
kind: Pod
metadata:
  name: mc-pod
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - image: nginx:1.22
    name: nginx1
    ports:
    - port: 80
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - image: debian:11
    name: debian2
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 1;
        done